const mutationTypes = {
  SET_USERS_SUCCESS: 'SET_USERS_SUCCESS',
  SET_USERS_FAIL: 'SET_USERS_FAIL',
  CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_USERS_TOTAL_COUNT: 'SET_USERS_TOTAL_COUNT'
};

export default mutationTypes;
